<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gwd-taparea_LEARN MORE_gwd-taparea_1</name>
   <tag></tag>
   <elementGuidId>cd64e8eb-7ac0-4e56-8474-1f7ae90470d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gwd-taparea[@id='gwd-taparea_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwd-taparea_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gwd-taparea</value>
      <webElementGuid>dde8019a-04e6-49db-a745-7d3cdd1644b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwd-taparea_1</value>
      <webElementGuid>89f32389-e458-419d-b528-7b81fc48bb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwd-taparea-b291</value>
      <webElementGuid>90d2b312-9866-4410-becb-89866b37dc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwd-taparea_1&quot;)</value>
      <webElementGuid>77aefd2e-3a0b-4777-bd11-24e6ed06f1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AlertObjects/Page_W3Schools Tryit Editor/iframe_concat(id(, , 200_276_express_html_inpage_0.if, , ))_200_276_express_html_inpage_0.if</value>
      <webElementGuid>4c7e4c0c-2ea8-48a2-a0d2-faba43cd9e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//gwd-taparea[@id='gwd-taparea_1']</value>
      <webElementGuid>c1e80e48-b277-40e4-b9fb-75d889cdcdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//gwd-page[@id='page1']/div/gwd-taparea</value>
      <webElementGuid>1517e88c-d2c0-4eff-b6b1-9a1f32f91130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gwd-taparea</value>
      <webElementGuid>4861ca21-1ec9-4c01-a2c5-bf069b3dcd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//gwd-taparea[@id = 'gwd-taparea_1']</value>
      <webElementGuid>4577a15a-5e25-4367-bafc-721e54a2e67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
