<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , 200_276_express_html_inpage_0.if, , ))_200_276_express_html_inpage_0.if</name>
   <tag></tag>
   <elementGuidId>4dc43b8c-1be6-4e31-8964-6aac952510ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='200_276_express_html_inpage_0.if']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b94b33b3-8e10-47a2-b784-77ea8b8ff953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>200_276_express_html_inpage_0.if</value>
      <webElementGuid>5f87558c-a849-4ab4-a4df-92bd8d86d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s0.2mdn.net/sadbundle/742146653795283203/index.html</value>
      <webElementGuid>21414bc8-b90c-43a7-826d-cdd744094450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>0d972da2-fc20-4043-8878-3d8c85b5cdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>9eefcd0c-4431-4f94-b586-383bacd024d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c5a1f41-2ccb-4f47-932a-de6b1fd10cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fac93c2b-bbdc-4ac7-bf28-68f886ac2109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8660d089-6968-47f2-addf-ec2d59c54217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;200_276_express_html_inpage_0.if&quot;)</value>
      <webElementGuid>18a5452a-bf59-4c6f-885a-c6e9fac7b539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AlertObjects/Page_W3Schools Tryit Editor/iframe_Run_google_ads_iframe_16833175TryitL_c705de</value>
      <webElementGuid>e1823a67-1666-48f3-9345-ffad3d967e90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='200_276_express_html_inpage_0.if']</value>
      <webElementGuid>cc757cb7-f6e6-48b2-9f51-62c57bdc6526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dclk-studio-creative_1669736703374']/div/iframe</value>
      <webElementGuid>b993717b-ec48-4bd1-993c-f27ee37def74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>c66c1530-1cc7-4914-a90c-52cf7225e2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = '200_276_express_html_inpage_0.if' and @src = 'https://s0.2mdn.net/sadbundle/742146653795283203/index.html']</value>
      <webElementGuid>3daeb41d-efa1-487b-816b-9e6e2f572220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
