<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_addtocart_36.EnteredQuantity</name>
   <tag></tag>
   <elementGuidId>54ddde6b-d5c0-46b8-af4e-285698ae72a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addtocart_36_EnteredQuantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addtocart_36_EnteredQuantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>276352f9-1556-4f85-9277-0d26046b941f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>e0857f96-f340-484a-ac7a-e831fafc478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c71c651-d503-4c09-a07a-d5471f8633c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Qty must be a number.</value>
      <webElementGuid>792b9d4a-493b-4f82-a207-7e6273b62842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addtocart_36_EnteredQuantity</value>
      <webElementGuid>ff77bace-c7fa-467b-ba44-14723d786805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_36.EnteredQuantity</value>
      <webElementGuid>2481b373-c8ca-4afe-b7c2-f8b1c213f42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7d23d16-94d4-4eee-a871-2a942810c8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>61a29308-2c8f-42af-8e87-cc89ed57b13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addtocart_36_EnteredQuantity&quot;)</value>
      <webElementGuid>6e90b5cb-ceac-415c-86c3-9c6f5812afb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addtocart_36_EnteredQuantity']</value>
      <webElementGuid>52e07497-4320-455b-a188-e94899507e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/input</value>
      <webElementGuid>3b6728b8-5e72-4187-bbdc-52b9a609730e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>3a979936-1ba9-4f89-a8a1-ffce29c51f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addtocart_36_EnteredQuantity' and @name = 'addtocart_36.EnteredQuantity' and @type = 'text']</value>
      <webElementGuid>77a5e74b-a7e7-44f4-8cd0-ce5148873bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
