<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageListFrame</name>
   <tag></tag>
   <elementGuidId>4c89ca97-bbe7-4e86-9ff8-935ef3b09a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageListFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageListFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4413ddba-970d-4ca7-bdf1-2c1973d774ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-frame.html</value>
      <webElementGuid>ace5c927-ff81-41c9-88d4-fd6afdef0904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageListFrame</value>
      <webElementGuid>e2985b28-2d9b-45cb-be2c-d372f559bfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Packages</value>
      <webElementGuid>0bc4d3c6-cee7-4c4e-abac-7e9f32de4cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftTop&quot;]/iframe[1]</value>
      <webElementGuid>f335c54f-e039-4dd5-87ea-8f1c693e1859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageListFrame']</value>
      <webElementGuid>3a7c562e-82d2-45c8-b56f-7b884efd1c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ae736930-7cb7-43bf-bcae-6fdc01c78261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-frame.html' and @name = 'packageListFrame' and @title = 'All Packages']</value>
      <webElementGuid>05900038-e674-4c23-98a0-5f16d08c8248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
